window.__env = {
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  TMDB_API_KEY: '',
  SPOTIFY_CLIENT_ID: '',
  FIREBASE_API_KEY: '',
  FIREBASE_AUTH_DOMAIN: '',
  FIREBASE_PROJECT_ID: '',
  FIREBASE_STORAGE_BUCKET: '',
  FIREBASE_MESSAGING_SENDER_ID: '',
  FIREBASE_APP_ID: '',
  FIREBASE_MEASUREMENT_ID: '',
  AI_API_KEY: ''
};
